### ISSUE TITLE
[Icons] Verschiedene Launcher Icons anbieten

### ISSUE THREAD

**Issue by markusressel** [Power-Switch/PowerSwitch_Android#43]
"... achso ich würde mir ein Homescreen- Icon wie in der "alten" Version wünschen. Oder zumindest Transparent.﻿"

**Comment by markusressel** [comment]
Es ist nicht angedacht das Launcher Icon zur Laufzeit ändern zu können, es gibt allerdings einen Trick mit dem es trotzdem gehen soll (allerdings nicht auf allen Android Versionen getestet, könnte zu Problemen führen)

Hack:
http://stackoverflow.com/a/20851946

**Comment by ccMatrix** [comment]
https://www.chainfire.eu/articles/133/_TUT_Supporting_multiple_icons_in_your_app/

So macht es SuperSU und es funktioniert hervorragend.

**Comment by markusressel** [comment]
Danke :) Werd ich mir bei Gelegenheit ansehen.

**Comment by markusressel** [comment]
@ccMatrix So ist es auch auf Stackoverflow beschrieben. Ich hatte mich erstmal dagegen entschieden, weil es möglicherweise auf einigen Geräten zu Problemen führen könnte.

Ich habe es jetzt aber mal eingebaut, auf meinen Testgeräten funktioniert es wie erwartet.
