### ISSUE TITLE
Setting repeat (command) count per Receiver

### ISSUE THREAD

**Issue by Paul-Vdp** [Power-Switch/PowerSwitch_Android#57]
It would be useful to provide an extra parameter per receiver, indicating the number of times to send/repeat the corresponding command.
Thing is I notice that sometimes things do not activate upon first try, but do after one or more repeats. Due to distance from the gateway, awkward receiver placement, ...
In the old version there was the general option to send everything twice - which helped - but I imagine did not play well with dimmers, shutters and so on.
A more specific option (per receiver a 'repeat count') would certainly be a nice-to-have option.

**Comment by markusressel** [comment]
It is now possible to set the repeat amount of network signals that will be sent when tapping a button (or executing an action from somewhere else) on a per receiver basis in the ConfigureReceiverDialog.

**Comment by Paul-Vdp** [comment]
Hi Markus,

 

Great – once again. Thanks for fulfilling another wish ;-)

However : I cannot find the new feature ? And cannot say I noticed any app update coming through recently ?

 

Best regards,

Paul

**Comment by markusressel** [comment]
Yes, because this feature is still in dev branch only. I have very little time at the moment (thanks to work and university) and still need to test some things before I can merge this to beta branch. So unfortunately you have to be patient just a little longer :)

**Comment by Paul-Vdp** [comment]
OK Markus, no problemo. Take your time – work and uni come first …

Wishing you lots of success with both !
