### ISSUE TITLE
Publish APKs on Github

### ISSUE THREAD

**Issue by IzzySoft** [Power-Switch/PowerSwitch_Android#67]
Wäre toll für die Leutz, die ihre Geräte ohne GApps betreiben, die App direkt hier herunterladen zu können. Am besten direkt über die `releases/` Seite. Wie schaut's aus? :smiley_cat:

**Comment by markusressel** [comment]
Apks sind vorerst im Ordner "APKs" zu finden.
Über Releases muss ich mich noch informieren.

**Comment by IzzySoft** [comment]
Bei den Releases lassen sich zusätzliche Dateien einfach anfügen (den "Edit" Button neben dem entsprechenden Release anklicken, dann siehe *Attach binaries by dropping them here or selecting them.* ;). Aber ein "APKs" Ordner wäre auch schon einmal etwas (da ich ihn noch nicht sehe, kommt er wohl erst noch? Alternativ kannst Du natürlich auch erstmal bei den Releases schauen, da wären "Blobs" ohnehin besser aufgehoben – und den "APKs" Ordner im "source tree" als "Fallback" im Hinterkopf haben. Auf einen Tag kommt's ja nicht an :)

Danke schonmal!

**Comment by markusressel** [comment]
dev branch...

**Comment by IzzySoft** [comment]
Oi... OK, tnx!

**Comment by markusressel** [comment]
Releases existieren nun ab Version 1.1.0 .
Frühere Versionen können auf https://power-switch.eu/download/ oder im Sourcecode Ordner "APKs" heruntergeladen werden.

**Comment by IzzySoft** [comment]
Riesendank!
