### ISSUE TITLE
[Szenen]  

### ISSUE THREAD

**Issue by Zosche** [Power-Switch/PowerSwitch_Android#79]
Bei mir lassen sich bei Szenen die gewählten Empfänger trotz gewählter Option "aus" nur alle einschalten.
Ich speichere die Empfänger mit der Option "aus" und beim erneuten Aufruf der Szene stehen alle auf "ein".

**Comment by markusressel** [comment]
Kann ich ohne weitere Infos leider nicht nachstellen.
Da ich aktuell aber einiges umbaue was die Konfigurationsdialoge und das Speichern aller Daten betrifft ist das erstmal geschlossen.
