### ISSUE TITLE
Widgets: Beschriftung unlesbar bei dunklen Hintergründen

### ISSUE THREAD

**Issue by hippeland** [Power-Switch/PowerSwitch_Android#82]
Die Beschriftung der Widgets ist auf dunklem Hintergrund nicht lesbar

Version 1.6.6 (102)

![_20170401_121419](https://cloud.githubusercontent.com/assets/26835446/24577904/126ff6ce-16d7-11e7-93e6-a5d88e2bcaa7.JPG)

**Comment by markusressel** [comment]
Eigentlich sollte die Schrift weiß sein. Ist aber erst seit neueren Android versionen so.
