### ISSUE TITLE
Wie sendet man an das ITGW 433 mit Java Signale

### ISSUE THREAD

**Issue by BrummBrumm03** [Power-Switch/PowerSwitch_Android#84]
Hallo, kann mir einer erklären wie ich mir eine API schreibe mit Java mit der ich am Intertechno Gateway mit LAN meine Stecker schalte?
MfG
Ich benötige: 
UPD Socket:

	public void send(String ip, String msg) {
		try {
			@SuppressWarnings("resource")
			DatagramSocket socket = new DatagramSocket();
			socket.connect(InetAddress.getByName(ip), 49880);
			byte[] buffer = msg.getBytes();
			socket.send(new DatagramPacket(buffer, buffer.length));
			
			DatagramPacket packet = new DatagramPacket(buffer, buffer.length);
	        socket.receive(packet);
	        System.out.println("Empfangen: " + new String(packet.getData()));
		} catch(Exception ex) {}
	}

So weit bin ich... kann mir jemand alle Strings zum senden für die Intertechno´s geben?
Soweit bin ich damit:

	public static String getAlphabeticSignalMaster(String master) {
		 String lo = "4,";
	        String hi = "12,";
	        String seqLo = lo + hi + lo + hi;
	        String seqFl = lo + hi + hi + lo;
	        String h = seqFl;
	        String l = seqLo;
	        String mus = "";

	        if(master.equalsIgnoreCase("A")) {
	        	mus = l + l + l + l;
	        } else if(master.equalsIgnoreCase("B")) {
	        	mus = h + l + l + l;
	        } else if(master.equalsIgnoreCase("C")) {
	        	mus = l + h + l + l;
	        } else if(master.equalsIgnoreCase("D")) {
	        	mus = h + h + l + l;
	        } else if(master.equalsIgnoreCase("E")) {
	        	mus = l + l + h + l;
	        } else if(master.equalsIgnoreCase("F")) {
	        	mus = h + l + h + l;
	        } else if(master.equalsIgnoreCase("G")) {
	        	mus = l + h + h + l;
	        } else if(master.equalsIgnoreCase("H")) {
	        	mus = h + h + h + l;
	        } else if(master.equalsIgnoreCase("I")) {
	        	mus = l + l + l + h;
	        } else if(master.equalsIgnoreCase("J")) {
	        	mus = h + l + l + h;
	        } else if(master.equalsIgnoreCase("K")) {
	        	mus = l + h + l + h;
	        } else if(master.equalsIgnoreCase("L")) {
	        	mus = h + h + l + h;
	        } else if(master.equalsIgnoreCase("M")) {
	        	mus = l + l + h + h;
	        } else if(master.equalsIgnoreCase("N")) {
	        	mus = h + l + h + h;
	        } else if(master.equalsIgnoreCase("O")) {	        	 
	        	mus = l + h + h + h;
	        } else if(master.equalsIgnoreCase("P")) {
	        	mus = h + h + h + h;
	        }
	        return mus;
	}
	
	public static String getNumericSignalSlave(String master) {
		 String lo = "4,";
	        String hi = "12,";
	        String seqLo = lo + hi + lo + hi;
	        String seqFl = lo + hi + hi + lo;
	        String h = seqFl;
	        String l = seqLo;
	        String mus = "";

	        if(master.equalsIgnoreCase("1")) {
	        	mus = l + l + l + l;
	        } else if(master.equalsIgnoreCase("2")) {
	        	mus = h + l + l + l;
	        } else if(master.equalsIgnoreCase("3")) {
	        	mus = l + h + l + l;
	        } else if(master.equalsIgnoreCase("4")) {
	        	mus = h + h + l + l;
	        } else if(master.equalsIgnoreCase("5")) {
	        	mus = l + l + h + l;
	        } else if(master.equalsIgnoreCase("6")) {
	        	mus = h + l + h + l;
	        } else if(master.equalsIgnoreCase("7")) {
	        	mus = l + h + h + l;
	        } else if(master.equalsIgnoreCase("8")) {
	        	mus = h + h + h + l;
	        } else if(master.equalsIgnoreCase("9")) {
	        	mus = l + l + l + h;
	        } else if(master.equalsIgnoreCase("10")) {
	        	mus = h + l + l + h;
	        } else if(master.equalsIgnoreCase("11")) {
	        	mus = l + h + l + h;
	        } else if(master.equalsIgnoreCase("12")) {
	        	mus = h + h + l + h;
	        } else if(master.equalsIgnoreCase("13")) {
	        	mus = l + l + h + h;
	        } else if(master.equalsIgnoreCase("14")) {
	        	mus = h + l + h + h;
	        } else if(master.equalsIgnoreCase("15")) {	        	 
	        	mus = l + h + h + h;
	        } else if(master.equalsIgnoreCase("16")) {
	        	mus = h + h + h + h;
	        }
	        return mus;
	}

Die Frage ist wie ich hier heraus die MSG bekomme die ich an die Gateway senden Muss

**Comment by markusressel** [comment]
Den Code zum senden der UDP Pakete findest du hier:

https://github.com/Power-Switch/PowerSwitch_Android/blob/master/Smartphone/src/main/java/eu/power_switch/network/NetworkPackageQueueHandler.java#L184

Die Implementierung für die alte master/slave codierung von Intertechno kannst du in dieser Klasse nachsehen:

https://github.com/Power-Switch/PowerSwitch_Android/blob/master/Smartphone/src/main/java/eu/power_switch/obj/receiver/device/intertechno/CMR1000.java

Allerdings ist diese Art der Code Berechnung nicht sehr nah an der Hardware. Alternativ kannst du dir mal diesen (Python-)Code aus der ```raspyrfm-client``` library ansehen:

Basisklasse:
https://github.com/markusressel/raspyrfm-client/blob/master/raspyrfm_client/device/manufacturer/universal/HX2262Compatible.py

Implementierung für CMR1000:
https://github.com/markusressel/raspyrfm-client/blob/master/raspyrfm_client/device/manufacturer/intertechno/CMR1000.py

Ist auf den ersten Blick vielleicht nicht so leicht zu verstehen, im endeffekt aber eine deutlich sinnvollere Variante die Codes zu berechnen.


Wenn du weitere fragen hast wende dich bitte ans Forum: forum.power-switch.eu
Gruß,
Markus
